services:
  mariadb:
    image: mariadb:10.6
    container_name: mlops_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: creditcard_db
      MYSQL_USER: mlops_user
      MYSQL_PASSWORD: mlops_pass
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: mlops_redis
    restart: always
    ports:
      - "6379:6379"

  airflow:
    image: apache/airflow:2.8.1
    container_name: mlops_airflow
    restart: always
    user: root
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    ports:
      - "8080:8080"
    volumes:
      - ../dags:/opt/airflow/dags
      - ../scripts:/opt/airflow/scripts
      - ../models:/opt/airflow/models
      - ../data:/opt/airflow/data
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin
               --firstname Admin --lastname User --role Admin
               --email admin@example.com &&
               airflow webserver & airflow scheduler"

volumes:
  mariadb_data: